### ISSUE TITLE
Show aggregated counts for US,Canada and Australia

### ISSUE THREAD

**Issue by RamPrasadMeenavalli** [RamPrasadMeenavalli/react-covid19-tracker#1]
For some countries the data is reported for each state/province.
When a user doesn't select a state/province, the webpart should aggregate the counts from all states for that country and display the stats.

**Comment by harveysm** [comment]
Was working a few days ago, but it seems to have broke in the past day or so. It now shows "failed to fetch" error. Thanks for your work.

**Comment by RamPrasadMeenavalli** [comment]
I have released an update, which shows country level stats and supports selecting multiple countries. Please deploy the latest package and see if it helps.
